name: NPM Publish

on:
  push:
    branches: [master]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Get Node Version from NVM
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - run: yarn --immutable

      - run: yarn build
        env:
          NODE_ENV: production

      - name: Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
