name: NPM Publish

on:
  push:
    branches: [master]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - run: yarn --immutable

      - run: yarn build
        env:
          NODE_ENV: production

      - name: Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
